targets:
  $default:
    builders:
      auto_route_generator:auto_router_generator:
        generate_for:
          - lib/src/config/router/app_router.dart 
          - lib/src/presentation/**/**_view.dart